apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webpage
  name: webpage
  selfLink: /api/v1/namespaces/default/services/webpage
spec:
  externalTrafficPolicy: Local
  ports:
  - name: cce-service-0
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: webpage
  sessionAffinity: None
  type: NodePort

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: webpage
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/webpage
  labels:
    appgroup: ''
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webpage
      annotations:
        metrics.alpha.kubernetes.io/custom-endpoints: '[{"api":"","path":"","port":"","names":""}]'
    spec:
      containers:
        - name: container-0
          image: WEBAPP_IMAGE
          env:
            - name: PAAS_APP_NAME
              value: webpage
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: 05dfb004ce0025db2f6fc000f7114d04
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: default-secret
      affinity: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
      dnsConfig:
        options:
          - name: single-request-reopen
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
